version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./config:/app/config
    depends_on:
      - db
    environment:
      - GO_ENV=${ENVIRONMENT:-development}

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

volumes:
  postgres_data: